### ISSUE TITLE
Missing Typo :)

### ISSUE THREAD

**Issue by psbss** [shimataro/ssh-key-action#140]
https://github.com/shimataro/ssh-key-action#ssh-failed-even-though-key-has-been-installed

> Host key verification failed.:
> Set known_hosts ~~option~~ is correctly (use ssh-keyscan command).

known_hosts is needed in this package. so maybe this is missing typo.

**Comment by shimataro** [comment]
@psbss 
指摘ありがとうございます！v1の時点では省略できたので、必須化してから直し忘れてました…
optionじゃなくてparameterのほうがよさそうですね。
