### ISSUE TITLE
 node_modules/@actions/core is committed & node_modules isn't included in .gitignore

### ISSUE THREAD

**Issue by tats-u** [shimataro/ssh-key-action#157]
`npm install` installs a lot of files in `node_modules`, and they are tracked by Git.  We may add them to new commits by mistake.
Actually, `node_modules/@actions/core` has already been committed.  Is this intended?

🇯🇵
`npm install`は`node_module`に大量のファイルをインストールするため、Gitに追跡されてしまいます。これでは間違ってコミットしてしまいます。実際、`node_modules/@actions/core`がコミットされてしまっています。これは意図的なものでしょうか？

**Comment by tats-u** [comment]
This is because tsc alone cannot bundle dependencies, and I solved it by using ncc (#163).
tscだけでは依存性のバンドルができないのが原因ですが、nccを利用することによって解決しました。 (#163)

**Comment by tats-u** [comment]
Oh, it has not been merged in `develop` yet.  I will close this issue again at that time.
あ、まだ`develop`にはマージされていないのですね、そのタイミングで再クローズします。

**Comment by shimataro** [comment]
done!
