### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by serhii-baksheiev** [shimataro/ssh-key-action#159]
Hi guys, I tried to run sh script using your action but couldn't. Can you help me find what I did wrong? 
Here is the key and host I added and my yml file. Thank you!
<img width="467" alt="Screenshot 2020-10-30 at 17 58 41" src="https://user-images.githubusercontent.com/22969597/97727881-9120bf80-1ad9-11eb-8c36-66f4c80a82a0.png">
<img width="566" alt="Screenshot 2020-11-01 at 14 45 22" src="https://user-images.githubusercontent.com/22969597/97803158-e0d5c700-1c50-11eb-8162-79f3af0c42bb.png">
<img width="517" alt="Screenshot 2020-11-01 at 11 54 01" src="https://user-images.githubusercontent.com/22969597/97799860-0e167b00-1c39-11eb-8753-5ab67dfdc874.png">
<img width="532" alt="Screenshot 2020-11-01 at 11 55 25" src="https://user-images.githubusercontent.com/22969597/97799890-30a89400-1c39-11eb-9bbd-763378bc2406.png">

**Comment by samcarswell** [comment]
Same problem here.

![image](https://user-images.githubusercontent.com/47140276/97817241-3eb8ec00-1cef-11eb-9d97-6f79ec48ebfd.png)

![image](https://user-images.githubusercontent.com/47140276/97817279-6d36c700-1cef-11eb-9123-ea484d7bbf7f.png)

**Comment by samcarswell** [comment]
> Same problem here.
> 
> ![image](https://user-images.githubusercontent.com/47140276/97817241-3eb8ec00-1cef-11eb-9d97-6f79ec48ebfd.png)
> 
> ![image](https://user-images.githubusercontent.com/47140276/97817279-6d36c700-1cef-11eb-9123-ea484d7bbf7f.png)

Can confirm this was actually an issue with the host key generated with `ssh-keyscan`. I copied a host key from a machine that I knew had a working SSH connection to the server in question and it is now working fine.

**Comment by serhii-baksheiev** [comment]
> > Same problem here.
> > ![image](https://user-images.githubusercontent.com/47140276/97817241-3eb8ec00-1cef-11eb-9d97-6f79ec48ebfd.png)
> > ![image](https://user-images.githubusercontent.com/47140276/97817279-6d36c700-1cef-11eb-9123-ea484d7bbf7f.png)
> 
> Can confirm this was actually an issue with the host key generated with `ssh-keyscan`. I copied a host key from a machine that I knew had a working SSH connection to the server in question and it is now working fine.

Have you solved it?  Could you please share a solution with me?

**Comment by samcarswell** [comment]
Sorry I don't have an exact solution, but if you copy a host key from a server which has successfully connected with ssh and automatically added the key to `known_hosts`, it should work.

**Comment by serhii-baksheiev** [comment]
> Sorry I don't have an exact solution, but if you copy a host key from a server which has successfully connected with ssh and automatically added the key to `known_hosts`, it should work.

Actually, I tried this command ssh -T git@github.com, and the key was automatically added to my known_hosts file. And it still doesn't work...
<img width="566" alt="Screenshot 2020-11-09 at 14 05 46" src="https://user-images.githubusercontent.com/22969597/98540001-e60cc480-2295-11eb-89ec-47acc959f42f.png">

**Comment by samcarswell** [comment]
> > Sorry I don't have an exact solution, but if you copy a host key from a server which has successfully connected with ssh and automatically added the key to `known_hosts`, it should work.
> 
> Actually, I tried this command ssh -T [git@github.com](mailto:git@github.com), and the key was automatically added to my known_hosts file. And it still doesn't work...
> <img alt="Screenshot 2020-11-09 at 14 05 46" width="566" src="https://user-images.githubusercontent.com/22969597/98540001-e60cc480-2295-11eb-89ec-47acc959f42f.png">

I'm assuming by the name of your shell script, `deploy_to_aws.sh`, you'll want to run that command for your AWS server rather than GitHub.

**Comment by serhii-baksheiev** [comment]
> > > Sorry I don't have an exact solution, but if you copy a host key from a server which has successfully connected with ssh and automatically added the key to `known_hosts`, it should work.
> > 
> > 
> > Actually, I tried this command ssh -T [git@github.com](mailto:git@github.com), and the key was automatically added to my known_hosts file. And it still doesn't work...
> > <img alt="Screenshot 2020-11-09 at 14 05 46" width="566" src="https://user-images.githubusercontent.com/22969597/98540001-e60cc480-2295-11eb-89ec-47acc959f42f.png">
> 
> I'm assuming by the name of your shell script, `deploy_to_aws.sh`, you'll want to run that command for your AWS server rather than GitHub.


Oh yeah, you are right, I just took a screenshot in another terminal, here is the correct one. But the problem is still here (<img width="707" alt="Screenshot 2020-11-10 at 10 35 47" src="https://user-images.githubusercontent.com/22969597/98649654-80c1dd80-2340-11eb-8180-b9e5b6cbc536.png">

**Comment by samcarswell** [comment]
> > > > Sorry I don't have an exact solution, but if you copy a host key from a server which has successfully connected with ssh and automatically added the key to `known_hosts`, it should work.
> > > 
> > > 
> > > Actually, I tried this command ssh -T [git@github.com](mailto:git@github.com), and the key was automatically added to my known_hosts file. And it still doesn't work...
> > > <img alt="Screenshot 2020-11-09 at 14 05 46" width="566" src="https://user-images.githubusercontent.com/22969597/98540001-e60cc480-2295-11eb-89ec-47acc959f42f.png">
> > 
> > 
> > I'm assuming by the name of your shell script, `deploy_to_aws.sh`, you'll want to run that command for your AWS server rather than GitHub.
> 
> Oh yeah, you are right, I just took a screenshot in another terminal, here is the correct one. But the problem is still here (<img alt="Screenshot 2020-11-10 at 10 35 47" width="707" src="https://user-images.githubusercontent.com/22969597/98649654-80c1dd80-2340-11eb-8180-b9e5b6cbc536.png">

Sorry I meant run the command on your local machine directed to the AWS server you need the GitHub action to SSH to. eg. `ssh -T [AWS_HOST]`

**Comment by serhii-baksheiev** [comment]
> > > > > Sorry I don't have an exact solution, but if you copy a host key from a server which has successfully connected with ssh and automatically added the key to `known_hosts`, it should work.
> > > > 
> > > > 
> > > > Actually, I tried this command ssh -T [git@github.com](mailto:git@github.com), and the key was automatically added to my known_hosts file. And it still doesn't work...
> > > > <img alt="Screenshot 2020-11-09 at 14 05 46" width="566" src="https://user-images.githubusercontent.com/22969597/98540001-e60cc480-2295-11eb-89ec-47acc959f42f.png">
> > > 
> > > 
> > > I'm assuming by the name of your shell script, `deploy_to_aws.sh`, you'll want to run that command for your AWS server rather than GitHub.
> > 
> > 
> > Oh yeah, you are right, I just took a screenshot in another terminal, here is the correct one. But the problem is still here (<img alt="Screenshot 2020-11-10 at 10 35 47" width="707" src="https://user-images.githubusercontent.com/22969597/98649654-80c1dd80-2340-11eb-8180-b9e5b6cbc536.png">
> 
> Sorry I meant run the command on your local machine directed to the AWS server you need the GitHub action to SSH to. eg. `ssh -T [AWS_HOST]`

Oh, it was so stupid of my side, thank you so much, I'm very grateful to you! All works perfectly now!
