### ISSUE TITLE
Need to add `-r` or `-a` option for `rsync` command in the usage

### ISSUE THREAD

**Issue by northbright** [shimataro/ssh-key-action#193]
Hi @shimataro ,

The `rsync` command in the usage may need `-r` or `-a` option for directory syncing.

```
- name: rsync over ssh
  run: rsync -av ./foo/ user@remote:bar/
```

Your ssh-key-action saves me a lot of time, it's awesome!

**Comment by tats-u** [comment]
`-c` is also recommended if you do not use `git-restore-mtime` in https://github.com/MestreLion/git-tools.
I would also recommend `-z` (compress).

**Comment by shimataro** [comment]
Thank you for your suggestion! I added `-r` to usage.

`-a`, `-c`, and `-z` are also useful, but I omitted because they are not essential for transfer.
