### ISSUE TITLE
Update Node.js warning

### ISSUE THREAD

**Issue by dnwjn** [shimataro/ssh-key-action#207]
Hello,

When running a workflow containing the `shimataro/ssh-key-action@v2`, I receive the following warning:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: shimataro/ssh-key-action
```

**Comment by crstauf** [comment]
Occurs with `v2.3.1` also.

**Comment by benoitchantre** [comment]
I just published a [similar action inspired by this one](https://github.com/marketplace/actions/setup-ssh-authentication), but build as a composite action and with bash commands only.
You might want to give it a try.

**Comment by shimataro** [comment]
Thank you for your report!
I merged fix PR (#208, #216), new version will be released in a few days or weeks!

**Comment by lil5** [comment]
> I just published a [similar action inspired by this one](https://github.com/marketplace/actions/setup-ssh-authentication), but build as a composite action and with bash commands only.
> 
> You might want to give it a try.

@benoitchantre Could your more efficient version be merged into this project as version 3?

**Comment by benoitchantre** [comment]
> @benoitchantre Could your more efficient version be merged into this project as version 3?

@lil5 You can simply update your workflow to use my action. It’s quite straightforward. [Example](https://github.com/pi-hole/FTL/pull/1458/files).

**Comment by shimataro** [comment]
Information: new version [v2.4.0](https://github.com/shimataro/ssh-key-action/releases/tag/v2.4.0) is out!
