### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by doreybenjamin** [shimataro/ssh-key-action#219]
Hi,

I have warning like this when i use this action : 
uses: shimataro/ssh-key-action@v2

Result :
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: shimataro/ssh-key-action

**Comment by krystian-panek-vmltech** [comment]
yep, please upgrade

**Comment by shimataro** [comment]
Hi there,
new version [v2.4.0](https://github.com/shimataro/ssh-key-action/releases/tag/v2.4.0) is out!

It includes #208, that solves the problem.

closing.
