### ISSUE TITLE
Remove only specific ssh key after execution

### ISSUE THREAD

**Issue by techopswhiz** [shimataro/ssh-key-action#232]
Follow up to #199:

Thanks so much for the update #224. That will be very useful for some use cases.

I was wondering if removing the `.ssh` folder is a reliable cleanup process? What if IT has a few SSH keys preinstalled on that server? We don't want to delete them unless they were added by the action during this run.

**Comment by bambeusz** [comment]
the issue sounds similar to #231  

Just ran into this problem and spent some time wondering where did my `authorized_keys` file go.
Removing only the files that the action created would be awesome.

As a workaround I'm using previous version `2.4.0`, but the cleanup script is definitely a good thing to have.

**Comment by techopswhiz** [comment]
> Just ran into this problem and spent some time wondering where did my `authorized_keys` file go. Removing only the files that the action created would be awesome.

And lines that were added in existing files

**Comment by samuelneagu** [comment]
Hello,

Wanted to open an issue but noticed this one was already present. I run into the same issue. Could not figure out why the `authorized_keys` file was no longer on the runner; could no longer login to the runner(using the same user as the actions was using).

I agree the cleanup process is welcomed, but as bambeusz mentioned, would be good to remove only the key file that was created with the custom action, and under no circumstances the whole `.ssh` folder.

**Comment by nickmi** [comment]
Same issue my whole .ssh folder was purged on my self hosted runner... Please make it clear that you purge the whole .ssh folder on cleanup

**Comment by bambeusz** [comment]
![fine](https://i.imgflip.com/7ydn6q.jpg)

See #247

**Comment by shimataro** [comment]
Very sorry for the late reply.
This issue will be fixed in #251, which will be shipped soon.
