### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by epistrephein** [shimataro/ssh-key-action#266]
GitHub actions started displaying the following warning:

> [!WARNING]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: shimataro/ssh-key-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I suppose it's just a matter of bumping the versions in `build.yml` and `action.yml` as done in #208 at the time?

**Comment by shimataro** [comment]
Now [v2.7.0](https://github.com/shimataro/ssh-key-action/releases/tag/v2.7.0) supports Node.js 20. Thank you all!!
