### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by dennisedson** [shimataro/ssh-key-action#56]
Hi, i have this successfully adding the ssh keys, but when i attempt to test with a following step, i receive `Host key verification failed`. 
Before this command, i run `ls -a` on the .ssh folder and i do see the files... any thoughts? 

relevant code: 
```      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          public-key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: wpengine_rsa # optional
          # known-hosts: ${{ secrets.KNOWN_HOSTS }} # known_hosts; optional
      # config: ${{ secrets.CONFIG }} # ssh_config; optional
      - name: git test
        run: |
          cd /home/runner/.ssh
          ls -a
          ssh git@git.wpengine.com info

**Comment by shimataro** [comment]
@dennisedson 
Hello!
Thank you for your question.

> `Host key verification failed`

This error is due to lack of server key.
Key of `git.wpengine.com` seems to be:

```
|1|kzy0kmLAGlkcKWcskH8bLrtoTd4=|rSUtq1gGZNR4XlALV+8aJH9MF5E= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKPFgZ9SUnEqp6yVjT4plVEADyyO7/LQuVqAvOAKF24X1JDgQwT7Fge8daPQYiXZN6vN+UaPIyEGy8fY3xkYbhA=
|1|D9PmqnCqESllbTnZLBD8HnuA0P8=|tD+mbJQz6x04DtkObF+hkfzNZBY= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKPFgZ9SUnEqp6yVjT4plVEADyyO7/LQuVqAvOAKF24X1JDgQwT7Fge8daPQYiXZN6vN+UaPIyEGy8fY3xkYbhA=
```

Please add above values to your secrets (`secrets.KNOWN_HOSTS`) and uncomment below line:

```yaml
          # known-hosts: ${{ secrets.KNOWN_HOSTS }} # known_hosts; optional
```

**ONE MORE THING:**

If you set `name`, `ssh -i` option is also required in order to specify SSH key location.

```bash
ssh -i ~/.ssh/wpengine_rsa git@git.wpengine.com info
```

In most case, `name` can be omitted. In that case, you can omit `-i` option.

**Comment by dennisedson** [comment]
@shimataro , thanks for quick response.  this resolved my issue 💯

**Comment by spaquet** [comment]
@shimataro Is this the correct format for bitbucket.org in know_host:
bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==

I'm still receiving "Host key verification failed" while passing the above information.
