### ISSUE TITLE
Getting error when using the latest version

### ISSUE THREAD

**Issue by george3447** [shimataro/ssh-key-action#99]
Getting following error for the last 1 hour

Could not find file '/home/runner/work/_actions/_temp_16a41acc-ee83-42d0-8687-5ea6451234ef/_staging/shimataro-ssh-key-action-da773c8/node_modules/.bin/installed-package-contents'.

@shimataro Could you please look in to it, I think the last release is causing the issue.

**Comment by shimataro** [comment]
@george3447 
Thank you for your report.
I will fix it immediately.

**Comment by shimataro** [comment]
@george3447 
I have been released [v1.6.4](https://github.com/shimataro/ssh-key-action/releases/tag/v1.6.4) just now. How is it?

**Comment by george3447** [comment]
Hi @shimataro, thank you for the quick fix, I will check this in the evening and let you know

**Comment by george3447** [comment]
Hi @shimataro just checked the latest version #103 and it is working fine. Thank you so much for this action plugin and support. :100: :+1:

**Comment by shimataro** [comment]
@george3447, thank you TOO!
Closing this issue.
